spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&serverTimezone=UTC
    username: app
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never   # disable schema.sql auto-execution

  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

reservation:
  ttl-seconds: 3000 # 50 minutes

sweeper:
  cron: "0 */1 * * * *" # every 1 minute

grpc:
  server:
    port: 9091

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, info

# Logging for development
logging:
  level:
    root: INFO
    com.nuclei: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cache: DEBUG